DATE_FORMATS = ['short',
                'medium',
                'long',
                'full',
                'full',
                'full',
                'full',
                'full',
                'full',
                'full',
                'full',
                'full',
                'full',
                'd MMM YYY',
                'd MMMM YYY',
                'dd MMM YYY',
                'd MMM, YYY',
                'd MMMM, YYY',
                'dd, MMM YYY',
                'd MM YY',
                'd MMMM YYY',
                'MMMM d YYY',
                'MMMM d, YYY',
                'dd.MM.YY']

LOCALES = ['en_US']